events { worker_connections 1024; }

http {
    upstream backend_servers {
        server backend:5000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_servers/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 "Cloud Capstone: Nginx Reverse Proxy is Healthy\n";
        }
    }
}
